version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gemini-mongo-net

  springboot-app:
    build: ./backend/backend-task-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/task-app-test-gemini
    depends_on:
      - mongodb
    networks:
      - gemini-mongo-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"   
    depends_on:
      - springboot-app
    networks:
      - gemini-mongo-net

networks:
  gemini-mongo-net:

volumes:
  mongo_data: