version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - springboot-mongo-net

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/task-app-test-gemini
    depends_on:
      - mongodb
    networks:
      - springboot-mongo-net

networks:
  springboot-mongo-net:

volumes:
  mongo_data: